### ISSUE TITLE
defmutable - set!

### ISSUE THREAD

**Issue by netpyoung** [arcadia-unity/Arcadia#289] opened 2018-08-03 23:53 UTC
```clojure
(defprotocol P
  (foo [this]))

(defmutable A [^int a]
  P
  (foo [this]

       ;; that's what I expected expression on `deftype`
      ;; but it's not working.
       ;; (set! a 20) 

       (set! (.a this) 20) ;; it's work!
       ))
```

**Comment by timsgardner** [comment] 2018-08-27 20:57
This also fails:
```
(deftype B [^:unsynchronized-mutable ^int a]
  P
  (foo [this]
    (set! a 20)))
```

Seems to be a language bug, stay tuned.

**Comment by timsgardner** [comment] 2018-12-04 18:43
closing as duplicate of #294

**Closed by timsgardner** 2018-12-04 18:43 UTC
