### ISSUE TITLE
'Play' in editor hangs waiting for REPL

### ISSUE THREAD

**Issue by ikarth** [arcadia-unity/Arcadia#60] opened 2014-10-16 04:18 UTC
In Windows 7, I'm having an issue with the Unity Editor's play functionality and the REPL. Press 'Play' and the editor will hang waiting for a message from the REPL. Any command seems to work. 

To reproduce, in a new, properly set up project, with all of the Arcadia files under /Assets/Arcadia, .net 2.0 (not subset), and run-in-background on. Totally empty new scene. Connect a REPL client, via repl-client.rb. 

```
; Clojure Unity REPL
; Clojure 1.7.0-master-SNAPSHOT
; Unity 4.5.5f1 (7684ad0c5a44)
; Mono 2.0 (Visual Studio built mono)
nil

user=> (+ 1 1)
2 ; the command works

user=> (use 'arcadia.core)
nil

user=> (create-primitive :cube)
#<GameObject Cube (UnityEngine.GameObject)> ; Unity connection is fine

; press play here, Unity editor appears to hang

user=> (+ 1 1) ; enter any command here, press enter

; no response in the REPL. Unity will start play mode a few moments later. 
; REPL is hung, though; won't respond

;; You can start a new REPL client and it will connect just fine
;; But play mode will still freeze Unity without REPL input, and 
;; the REPL will freeze after sending the last command.

```

I did alter the path code in ClojureAssetPostprocessor.cs to work with Windows paths, which may or may not affect this. I'd be interested in hearing if other Windows users have observed this behavior. Note that I _don't_ get this when I open parade-route.

**Comment by sonelliot** [comment] 2015-01-22 11:26
I've been looking at this issue again now that [global game jam](http://globalgamejam.org/) 2015 is upon us! I'm pretty sure that Unity will hang when there is a thread that is blocking when it tries to reload the assemblies (i.e. after editing a script or when entering play mode).

You can reproduce this with:

```clojure
(defn do-thread! [proc]
  (doto (Thread. (gen-delegate ThreadStart [] (proc))) .Start))

(defn block-forever []
  (do-thread!
   (fn []
     (let [f (future (while true nil))]
       @f))))
```

Run ```(block-forever)``` somehow (i.e. REPL or add an editor button that triggers it) and you will find that Unity hangs if you hit play mode or modify a script file. If you open up ```Editor.log``` it will be stuck on this line:

> Reloading assemblies for play mode.
> Begin MonoManager ReloadAssembly

**Comment by nasser** [comment] 2015-01-22 22:10
Oh that makes sense, actually. As we understand it, when Unity enters play mode or reloads the assemblies it actually pulls the Mono VM out of memory and reinitializes it. It could be that if Mono has some non-resolved threads Unity waits for them to terminate before moving on. If the the there are threads that *never* terminate, e.g. your example or the REPL messing up, Unity might hang.

I'll dig around a bit in the next day or so to confirm or deny. Just to be sure, you're testing off of develop, not master, right?

**Comment by sonelliot** [comment] 2015-01-22 23:55
Sweet. I'm using the ```new-layout``` branch which I think is up-to-date with ```develop```.

**Comment by nasser** [comment] 2015-01-23 00:10
Good to know. We merged `new-layout` into `develop` a while back. Switch over when you can for the fixes we've made since then.

**Comment by nasser** [comment] 2015-01-28 08:06
This is fixed after todays pushes. Unity will still hang when you quit if the REPL is open on Windows 7. Still working on a fix for that...

**Closed by nasser** 2015-01-28 08:06 UTC
