### ISSUE TITLE
using `arcadia.literals` reader types in code breaks in build

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#277] opened 2018-04-24 15:41 UTC
Scenario was:
* top level def in `.clj` file with `#unity/Color [0.6863554 0.513454 0.2970535 1.0]` literals
* build errors from not finding reader for `#unity/Color`

Code loaded fine in editor.

**Comment by timsgardner** [comment] 2018-08-31 22:00
I'm not reproducing this. Did the file in question require `arcadia.core`?

**Comment by nasser** [comment] 2018-12-04 22:20
on the current `beta` the following namespace

```clj
(ns color
  (:use arcadia.core))

(def favorite-color #unity/value ["Color" 0.6863554 0.513454 0.2970535 1.0])

(defn log-favorite-color [go _]
  (log "my name is "
       (.name go)
       " and my favorite color is "
       favorite-color))
```

fails to AOT with

```
InvalidOperationException: Can't embed unreadable object in code: #<UnityEngine.Color RGBA(1.000, 0.297, 0.513, 0.686)>
clojure$core$load_libfn__25538__25542.invoke () (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$load_lib__25549.invokeStatic (System.Object , System.Object , clojure.lang.ISeq ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$load_lib__25549.doInvoke (System.Object , System.Object , System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <138b9d0b0b3f4982b42abdb2b77eda11>:0)
clojure$core$apply__19534.invokeStatic (System.Object , System.Object , System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$apply__19534.invoke (System.Object , System.Object , System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$load_libs__25574.invokeStatic (clojure.lang.ISeq ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$load_libs__25574.doInvoke (System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure.lang.RestFn.applyTo (clojure.lang.ISeq arglist) (at <138b9d0b0b3f4982b42abdb2b77eda11>:0)
clojure$core$apply__19534.invokeStatic (System.Object , System.Object , System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$apply__19534.invoke (System.Object , System.Object , System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$require__25596.invokeStatic (clojure.lang.ISeq ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure$core$require__25596.doInvoke (System.Object ) (at <0f47ef55b6284c9090d7b5b9ba53d099>:0)
clojure.lang.RestFn.invoke (System.Object arg1) (at <138b9d0b0b3f4982b42abdb2b77eda11>:0)
arcadia$compiler$aot_namespacesfn__8621__8629.invoke () (at <92fa19ca494a460a99149af1a690e608>:0)
arcadia$compiler$aot_namespaces__8639.invokeStatic (System.Object , System.Object , System.Object ) (at <92fa19ca494a460a99149af1a690e608>:0)
arcadia$compiler$aot_namespaces__8639.invoke (System.Object , System.Object , System.Object ) (at <92fa19ca494a460a99149af1a690e608>:0)
Arcadia.Util.Invoke (clojure.lang.Var v, System.Object a, System.Object b, System.Object c) (at Assets/Arcadia/Helpers/Util.cs:60)
Arcadia.BuildPipeline.CompileNamespacesToFolder (System.Collections.IEnumerable userNameSpaces, System.String targetFolder) (at Assets/Arcadia/Editor/BuildPipeline.cs:130)
Arcadia.BuildPipeline.BuildUser () (at Assets/Arcadia/Editor/BuildPipeline.cs:157)
```

**Comment by nasser** [comment] 2018-12-05 20:34
This is not a use case we can support in AOT without rethinking how the reader works, unfortunately. There *may be* some tricks we can pull down the line, but for now the simpler/safer thing to do is replace in-line reader literals with constructors, e.g.

```clj
(def favorite-color (UnityEngine.Color. 0.6863554 0.513454 0.2970535 1.0])
```

and leave the reader literals for serialization.

This is tricky because it will work in the REPL but not in AOT, which is surprising. The REPL and AOT have slightly different semantics when it comes to reader literals. Closing for now.

**Closed by nasser** 2018-12-05 20:34 UTC
Labels: bug
