### ISSUE TITLE
FileNotFoundException: Could not locate arcadia.repl.clj.dll or arcadia/repl.clj on load path.

### ISSUE THREAD

**Issue by acron0** [arcadia-unity/Arcadia#104] opened 2015-01-16 10:11 UTC
A fresh Unity project (4.6.1f, Pro, Trial) on Windows 8.1 produces this when trying to start the REPL. Code was pulled from GitHub ~10 mins ago.

```
System.IO.FileNotFoundException: Could not locate arcadia.repl.clj.dll or arcadia/repl.clj on load path.
  at clojure.lang.RT.load (System.String relativePath, Boolean failIfNotFound) [0x00000] in         <filename unknown>:0 
  at clojure.lang.RT.load (System.String relativePath) [0x00000] in <filename unknown>:0 
  at ClojureRepl.StartREPL () [0x00000] in C:\Users\Antony\Documents\Scratch\ArcadiaExample\Assets\Arcadia\Editor\ClojureRepl.cs:30 
  at ClojureRepl..cctor () [0x00005] in C:\Users\Antony\Documents\Scratch\ArcadiaExample\Assets\Arcadia\Editor\ClojureRepl.cs:16 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
```

I'll have a quick look at a fix but no promises.

**Comment by acron0** [comment] 2015-01-16 10:21
Ok, so it looks like this issue is a dupe of https://github.com/arcadia-unity/Arcadia/issues/44

Windows needs your love!

**Comment by timsgardner** [comment] 2015-01-17 23:20
It does! We're getting there...

**Comment by nasser** [comment] 2015-01-18 09:42
Yup yup. New label created just for Windows. We will fix it.

**Comment by 5alamander** [comment] 2015-10-15 09:13
Help...   o(╯□╰)o  ...

FileNotFoundException: Could not locate Arcadia.Scripts.new_component.clj.dll or Arcadia/Scripts/new_component.clj on load path.
clojure.lang.RT.load (System.String relativePath, Boolean failIfNotFound)
clojure.lang.RT.load (System.String relativePath)
clojure/core$load$fn__17938__17942.invoke ()
clojure/core$load__17945.doInvoke (System.Object )
clojure.lang.RestFn.invoke (System.Object arg1)
clojure/core$load_one__17818.invoke (System.Object , System.Object , System.Object )
clojure/core$compile$fn__17952__17956.invoke ()
clojure/core$compile__17959.invoke (System.Object )
clojure.lang.Var.invoke (System.Object arg1)
ClojureAssetPostprocessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/Arcadia/Editor/ClojureAssetPostprocessor.cs:87)
UnityEngine.Debug:LogException(Exception)
ClojureAssetPostprocessor:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/Arcadia/Editor/ClojureAssetPostprocessor.cs:92)
UnityEditor.DockArea:OnGUI()

**Comment by nasser** [comment] 2018-12-04 16:09
![](https://github.trello.services/images/mini-trello-icon.png) [Reproduce issue #104](https://trello.com/c/7SBJ4tia/17-reproduce-issue-104)

**Comment by nasser** [comment] 2018-12-04 21:17
Seems to be fixed as of the latest `beta`, Windows 10, Unity 2018.2.18f1. This likely got fixed along the way.

**Closed by nasser** 2018-12-04 21:17 UTC
Labels: bug, windows
